apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: codellama-7b
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
  name: codellama-7b
  namespace: rcarrata-llm
  finalizers:
    - inferenceservice.finalizers
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '10'
          memory: 20Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '6'
          memory: 16Gi
          nvidia.com/gpu: '1'
      runtime: codellama-7b
      storage:
        key: aws-connection-my-storage
        path: models/CodeLlama-7b-hf
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists