apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: codellama-7b
  annotations:
    serving.knative.openshift.io/enablePassthrough: 'false'
    sidecar.istio.io/inject: 'false'
    sidecar.istio.io/rewriteAppHTTPProbers: 'false'